
describe( "lookup_commit #commit", function() pending("luagi_commit_lookup") end)
describe( "commit #commit", function() pending("luagi_commit_create") end) 
describe( "id #commit", function() pending("luagi_commit_id ") end)
describe( "summary #commit", function() pending("luagi_commit_summary ") end)
describe( "message #commit", function() pending("luagi_commit_message ") end)
describe( "encoding #commit", function() pending("luagi_commit_encoding ") end)
describe( "committer #commit", function() pending("luagi_commit_committer ") end)
describe( "author #commit", function() pending("luagi_commit_author ") end)
describe( "tree #commit", function() pending("luagi_commit_tree ") end)
describe( "parent_count #commit", function() pending("luagi_commit_parentcount ") end)
describe( "parent #commit", function() pending("luagi_commit_parent ") end)
describe( "parent_id #commit", function() pending("luagi_commit_parent_id ") end)
describe( "ancestor #commit", function() pending("luagi_commit_nth_gen_ancestor ") end)
describe( "amend #commit", function() pending("luagi_commit_amend ") end)
