local luagi = require("luagi")

describe("global config #config", function()

   it( "should not be nil", function()
      local path = luagi:find_global_config()
      assert.is.not_nil( path )
   end)
end)

describe("config parse bool #config", function()

   it( "should be true", function()
      assert.is.True( luagi.parse_bool( "true" ) )
   end)

   it( "should be true", function()
      assert.is_true( luagi.parse_bool( "True" ) )
   end)

   it( "should be true", function()
      assert.is_true( luagi.parse_bool( "trUE" ) )
   end)

   it( "should be true", function()
      assert.is_true( luagi.parse_bool( "TRUE" ) )
   end)

   it( "should be false", function()
      assert.is_false( luagi.parse_bool( "False" ) )
   end)

   it( "should be false", function()
      assert.is_false( luagi.parse_bool( "false" ) )
   end)
   
   it( "should be false", function()
      assert.is_false( luagi.parse_bool( "FALSE" ) )
   end)

   it( "should be false", function()
      assert.is_false( luagi.parse_bool( "falSE" ) )
   end)
end)

describe( "parse_int32 #config", function()
   it( "should be 1", function()
      assert.is_equal( 1, luagi.parse_int32( "1" ))
   end)
   it( "should be 1", function()
      assert.is_equal( 1, luagi.parse_int32( "+1" ))
   end)
   it( "should be 0", function()
      assert.is_equal( 0, luagi.parse_int32( "0" ))
   end)
   it( "should be -1", function()
      assert.is_equal( -1, luagi.parse_int32( "-1" ))
   end)
   it( "should be 2147483647", function()
      assert.is_equal( 2147483647, luagi.parse_int32( "2147483647" ))
   end)
   it( "should be 2147483647", function()
      assert.is_equal( 2147483647, luagi.parse_int32( "+2147483647" ))
   end)
   it( "should be -2147483648", function()
      assert.is_equal( -2147483648, luagi.parse_int32( "-2147483648" ))
   end)
   it( "should have error", function()
      assert.has_error( function() luagi.parse_int32( "2147483648" ) end)
   end)
   it( "should have error", function()
      assert.has_error( function() luagi.parse_int32( "-2147483649") end )
   end)
end)

describe("parse_int64 #config", function()
   it("should be 1", function()
      assert.is_equal(1, luagi.parse_int64( "1" ) )
   end)

   it("should be 1", function()
      assert.is_equal(1, luagi.parse_int64( "+1" ) )
   end)

   it("should be 0", function()
      assert.is_equal(0, luagi.parse_int64( "0" ) )
   end)

   it("should be -1", function()
      assert.is_equal(-1, luagi.parse_int64( "-1" ) )
   end)

   it("should be 9223372036854775807", function()
      assert.is_equal( 9223372036854775807, luagi.parse_int64( "9223372036854775807" ) )
   end)

   it( "should have error", function()
      assert.has_error( function() luagi.parse_int64( "9223372036854775808" ) end )
   end)

   it("should be -9223372036854775807", function()
      assert.is_equal( -9223372036854775807, luagi.parse_int64( "-9223372036854775807" ) )
   end)

   it("should have error", function()
      assert.has_error( function() luagi.parse_int64( "-9223372036854775808" ) end )
   end)
end)


describe( "add_file_ondisk #config", function() pending("luagi_config_add_file_ondisk ") end)
describe( "open_level #config", function() pending("luagi_config_open_level ") end)
describe( "open_global #config", function() pending("luagi_config_open_global ") end)
describe( "snapshot #config", function() pending("luagi_config_snapshot ") end)
describe( "refresk #config", function() pending("luagi_config_refresh ") end)
describe( "get_entry #config", function() pending("luagi_config_get_entry ") end)
describe( "get_int32 #config", function() pending("luagi_config_get_int32 ") end)
describe( "get_int64 #config", function() pending("luagi_config_get_int64 ") end)
describe( "get_bool #config", function() pending("luagi_config_get_bool ") end)
describe( "get_string #config", function() pending("luagi_config_get_string ") end)
describe( "get_multivar #config", function() pending("luagi_config_get_mulitvar_foreach ") end)
describe( "iterator_new #config", function() pending("luagi_config_iterator_new ") end)
describe( "iterator_glob_new #config", function() pending("luagi_config_iterator_glob_new ") end)
describe( "multivar_iterator #config", function() pending("luagi_config_multivar_iterator ") end)
describe( "set_int32 #config", function() pending("luagi_config_set_int32 ") end)
describe( "set_int64 #config", function() pending("luagi_config_set_int64 ") end)
describe( "set_bool #config", function() pending("luagi_config_set_bool ") end)
describe( "set_string #config", function() pending("luagi_config_set_string ") end)
describe( "set_multivar #config", function() pending("luagi_config_set_multivar ") end)
describe( "delete_entry #config", function() pending("luagi_config_delete_entry ") end)
describe( "delete_multivar #config", function() pending("luagi_config_delete_mulitvar ") end)
describe( "foreach #config", function() pending("luagi_config_foreach ") end)
describe( "foreach_match #config", function() pending("luagi_config_foreach_match ") end)
describe( "get_mapped #config", function() pending("luagi_config_get_mapped ") end)
describe( "backend_foreach_match #config", function() pending("luagi_config_backend_foreach_match ") end)
