describe( "get_delta #patch", function() pending("luagi_patch_get_delta ") end)
describe( "num_hunks #patch", function() pending("luagi_patch_num_hunks ") end)
describe( "line_stats #patch", function() pending("luagi_patch_line_stats ") end)
describe( "get_hunk #patch", function() pending(" luagi_patch_get_hunk ") end)
describe( "num_lines_in_hunk #patch", function() pending("luagi_patch_num_lines_in_hunk ") end)
describe( "get_line_in_hunk #patch", function() pending("luagi_patch_get_line_in_hunk ") end)
describe( "size #patch", function() pending("luagi_patch_size ") end)
describe( "print #patch", function() pending("luagi_patch_print ") end)
describe( "to_buf #patch", function() pending(" luagi_patch_to_buf ") end)
describe( "patch_buffers #patch #base", function() pending("pending") end)
