   --remotes
describe( "is_valid_remote_name #remote", function() pending("pending") end)
describe( "is_valid_remote_url #remote", function() pending("pending") end)
describe( "is_supported_remote_url #remote", function() pending("pending") end)
describe( "remotes #remote", function() pending("luagi_remote_list") end)
describe( "load_remote #remote", function() pending("luagi_remote_load") end)
describe( "create_anon_remote #remote", function() pending("luagi_remote_create_anonymous") end)
describe( "create_remote_with_fetch #remote", function() pending("luagi_remote_create_with_fetchspec") end)
describe( "create_remote #remote", function() pending("luagi_remote_create") end)


describe( "save #remote", function() pending("              luagi_remote_save                    ") end)
describe( "owner #remote", function() pending("             luagi_remote_owner                   ") end)
describe( "name #remote", function() pending("              luagi_remote_name                    ") end)
describe( "url #remote", function() pending("               luagi_remote_url                     ") end)
describe( "pushurl #remote", function() pending("           luagi_remote_pushurl                 ") end)
describe( "set_url #remote", function() pending("           luagi_remote_set_url                 ") end)
describe( "set_pushurl #remote", function() pending("       luagi_remote_set_pushurl             ") end)
describe( "add_fetch #remote", function() pending("         luagi_remote_add_fetch               ") end)
describe( "fetch_refspecs #remote", function() pending("    luagi_remote_get_fetch_refspecs      ") end)
describe( "set_fetch_refspecs #remote", function() pending("luagi_remote_set_fetch_refspecs      ") end)
describe( "add_push #remote", function() pending("          luagi_remote_add_push                ") end)
describe( "get_push_refspecs #remote", function() pending(" luagi_remote_get_push_refspecs       ") end)
describe( "set_push_refspecs #remote", function() pending(" luagi_remote_set_push_refspecs       ") end)
describe( "clear_refspecs #remote", function() pending("    luagi_remote_clear_refspecs          ") end)
describe( "refspec_count #remote", function() pending("     luagi_remote_refspec_count           ") end)
describe( "get_refspec #remote", function() pending("       luagi_remote_get_refspec             ") end)
describe( "connect #remote", function() pending("           luagi_remote_connect                 ") end)
describe( "ls #remote", function() pending("                luagi_remote_ls                      ") end)
describe( "download #remote", function() pending("          luagi_remote_download                ") end)
describe( "fetch #remote", function() pending("             luagi_remote_fetch                   ") end)
describe( "is_connected #remote", function() pending("      luagi_remote_connected               ") end)
describe( "stop #remote", function() pending("              luagi_remote_stop                    ") end)
describe( "disconnect #remote", function() pending("        luagi_remote_disconnect              ") end)
describe( "check_cert #remote", function() pending("        luagi_remote_check_cert              ") end)
describe( "set_transport #remote", function() pending("     luagi_remote_set_transport           ") end)
describe( "set_callbacks #remote", function() pending("     luagi_remote_set_callbacks           ") end)
describe( "stats #remote", function() pending("             luagi_remote_stats                   ") end)
describe( "autotag #remote", function() pending("           luagi_remote_autotag                 ") end)
describe( "set_autotag #remote", function() pending("       luagi_remote_set_autotag             ") end)
describe( "rename #remote", function() pending("            luagi_remote_rename                  ") end)
describe( "fetch_head #remote", function() pending("        luagi_remote_update_fetch_head       ") end)
describe( "set_fetch_head #remote", function() pending("    luagi_remote_set_update_fetch_head   ") end)
describe( "update_tips #remote", function() pending("       luagi_remote_update_tips             ") end)
