
describe( "index #repo", function() pending("luagi_repository_index") end)
 describe( "head #repo", function() pending("luagi_repository_head") end)
describe( "is_head_detached #repo", function() pending("luagi_repository_head_detatched") end)
describe( "is_head_unborn #repo", function() pending("luagi_repository_head_unborn") end)
describe( "is_empty #repo", function() pending("luagi_repository_is_empty") end)
describe( "is_bare #repo", function() pending("luagi_repository_is_bare") end)
describe( "is_shallow #repo", function() pending("luagi_repository_is_shallow") end)
describe( "path #repo", function() pending("luagi_repository_path") end)
describe( "workdir #repo", function() pending("luagi_repository_workdir") end)
describe( "set_workdir #repo", function() pending("luagi_repository_set_workdir") end)
describe( "config #repo", function() pending(" luagi_repository_config") end)
describe( "config_snapshot #repo", function() pending("luagi_repository_config_snapshot") end)
describe( "odb #repo", function() pending("luagi_repository_odb") end)
describe( "refdb #repo", function() pending("luagi_repository_refdb") end)
describe( "message #repo", function() pending("luagi_repository_message") end)
describe( "remove_message #repo", function() pending("luagi_repository_message_remove") end)
describe( "cleanup_state #repo", function() pending("luagi_repository_state_cleanup") end)
describe( "foreach_fetchhead #repo", function() pending("luagi_repository_fetchhead_foreach") end)
describe( "foreach_mergehead #repo", function() pending("luagi_repository_mergehead_foreach") end)
describe( "hashfile #repo", function() pending("luagi_repository_hashfile") end)
describe( "set_head #repo", function() pending("luagi_repository_set_head") end)
describe( "set_head_detached #repo", function() pending("luagi_repository_set_head_detached") end)
describe( "detach_head #repo", function() pending("luagi_repository_detach_head") end)
describe( "state #repo", function() pending("luagi_repository_state") end)
describe( "set_namespace #repo", function() pending("luagi_repository_set_namespace") end)
describe( "get_namespache #repo", function() pending("luagi_repository_get_namespace") end)
