--revwalk
describe( "revwalk #revwalk", function() pending("luagi_revwalk_new") end)
describe( "reset #revwalk", function() pending("luagi_revwalk_reset ") end)
describe( "push #revwalk", function() pending("luagi_revwalk_push ") end)
describe( "push_glob #revwalk", function() pending("luagi_revwalk_push_glob ") end)
describe( "push_head #revwalk", function() pending("luagi_revwalk_push_head ") end)
describe( "hide #revwalk", function() pending("luagi_revwalk_hide ") end)
describe( "hide_glob #revwalk", function() pending("luagi_revwalk_hide_glob ") end)
describe( "hide_head #revwalk", function() pending("luagi_revwalk_hide_head ") end)
describe( "push_ref #revwalk", function() pending("luagi_revwalk_push_ref ") end)
describe( "hide_ref #revwalk", function() pending("luagi_revwalk_hide_ref ") end)
describe( "next #revwalk", function() pending(" luagi_revwalk_next ") end)
describe( "sorting #revwalk", function() pending("luagi_revwalk_sorting ") end)
describe( "push_range #revwalk", function() pending("luagi_revwalk_push_range ") end)
describe( "simplify_first_parent #revwalk", function() pending("luagi_revwalk_simplify_first_parent ") end)
describe( "repository #revwalk", function() pending("luagi_revwalk_repository ") end)
describe( "add_hide_callback #revwalk", function() pending(" luagi_revwalk_add_hide_callback ") end)
