describe( "lookup_submodule #submodule", function() pending(" luagi_submodule_lookup") end)
describe( "foreach_submodule #submodule", function() pending("luagi_submodule_foreach") end)
describe( "add_submodule_setup #submodule", function() pending("luagi_submodule_add_setup") end)
describe( "resolve_submodule_url #submodule", function() pending("luagi_submodule_resolve_url") end)
describe( "reload_all_submodules #submodule", function() pending("luagi_submodule_reload_all") end)

describe( "add_finalize #submodule", function() pending("luagi_submodule_add_finalize ") end)
describe( "name #submodule", function() pending("luagi_submodule_name ") end)
describe( "__tostring #submodule", function() pending("luagi_submodule_name ") end)
describe( "path #submodule", function() pending("luagi_submodule_path ") end)
describe( "url #submodule", function() pending("luagi_submodule_url ") end)
describe( "branch #submodule", function() pending("luagi_submodule_branch ") end)
describe( "set_url #submodule", function() pending("luagi_submodule_set_url ") end)
describe( "index_id #submodule", function() pending("luagi_submodule_index_id ") end)
describe( "head_id #submodule", function() pending("luagi_submodule_head_id ") end)
describe( "wd_id #submodule", function() pending("luagi_submodule_wd_id ") end)
describe( "ignore #submodule", function() pending("luagi_submodule_ignore ") end)
describe( "set_ignore #submodule", function() pending("luagi_submodule_set_ignore ") end)
describe( "update #submodule", function() pending("luagi_submodule_update ") end)
describe( "set_update #submodule", function() pending("luagi_submodule_set_update ") end)
describe( "fetch_recurse #submodule", function() pending("luagi_submodule_fetch_recurse_submodules ") end)
describe( "set_fetch_recurse #submodule", function() pending("luagi_submodule_set_fetch_recurse_submodules ") end)
describe( "init #submodule", function() pending("luagi_submodule_init ") end)
describe( "sync #submodule", function() pending("luagi_submodule_sync ") end)
describe( "reload #submodule", function() pending("luagi_submodule_reload ") end)
describe( "status #submodule", function() pending("luagi_submodule_status ") end)
describe( "location #submodule", function() pending("luagi_submodule_location ") end)
describe( "add_to_index #submodule", function() pending("luagi_submodule_add_to_index ") end)
describe( "save #submodule", function() pending("luagi_submodule_save ") end)
describe( "open_repository #submodule", function() pending("luagi_submodule_open ") end)
