
   --treeentry
describe( "treeentry_to_object #tree #treeentry", function() pending("luagi_tree_entry_to_object") end)
describe( "lookup_tree #tree", function() pending("luagi_tree_lookup") end) 
describe( "tree_builder #tree", function() pending("pending") end)
describe( "name #tree", function() pending("luagi_tree_entry_name ") end)
describe( "type #tree", function() pending("luagi_tree_entry_type ") end)
describe( "filemode #tree", function() pending("luagi_tree_entry_filemode ") end)
describe( "compare #tree", function() pending("luagi_tree_entry_cmp ") end)
describe( "id #tree", function() pending("luagi_tree_entry_id ") end)
describe( "clear #tree", function() pending("luagi_tree_builder_clear ") end)
describe( "entry_count #tree", function() pending("luagi_tree_builder_entry_count ") end)
describe( "get #tree", function() pending("luagi_tree_builder_get ") end)
describe( "insert #tree", function() pending("luagi_tree_builder_insert ") end)
describe( "remove #tree", function() pending("luagi_tree_builder_remove ") end)
describe( "write #tree", function() pending("luagi_tree_builder_write ") end)
describe( "filter #tree", function() pending("luagi_tree_builder_filter ") end)
describe( "id #tree", function() pending("luagi_tree_id ") end)
describe( "entry_count #tree", function() pending("luagi_tree_entrycount ") end)
describe( "entry_byname #tree", function() pending("luagi_tree_entry_byname ") end)
describe( "entry_byid #tree", function() pending("luagi_tree_entry_byid ") end)
describe( "entry_byindex #tree", function() pending("luagi_tree_entry_byindex ") end)
describe( "entry_bypath #tree", function() pending("luagi_tree_entry_bypath ") end)
describe( "walk #tree", function() pending("luagi_tree_walk ") end)
