#ifndef IS_LUAGI_DEFINES
#define IS_LUAGI_DEFINES

#define NAME "name"
#define OID "oid"
#define LOID "loid"
#define TARGET "target"
#define LOCAL "local"

#define EMAIL "email"
#define TIME "time"
#define TIME_OFF "time_offset"

#define ID "id"
#define SIZE "size"
#define FLAGS "flags"
#define MODE "mode"

#define STATUS "status"
#define SIMI "similarity"
#define NFILES "number_of_files"
#define OLD_FILE "old_file"
#define NEW_FILE "new_file"

#define BINARY "binary"
#define NOT_BINARY "not_binary"
#define VALID_ID "valid_id"

#define PATCH "patch"
#define HEADER "header"
#define RAW "raw"
#define NAME_ONLY "name_only"
#define NAME_STATUS "name_status"

#define ADDED "added"
#define DELETED "deleted"
#define MODIFIED "modified"
#define RENAMED "renamed"
#define COPIED "copied"
#define IGNORED "ignored"
#define UNTRACKED "untracked"
#define TYPECHANGE "typechange"

#define NONE "none"
#define NORMAL "normal"
#define UP_TO_DATE "up to date"
#define FASTFORWARD "fast forward"
#define UNBORN "unborn"

#define NO_FASTFORWARD "no fast forward"
#define FASTFORWARD_ONLY "fast forward only"

#define PATH "path"
#define CONTENT "content"
#define FORCE "force"
#define DISABLE_PATHSPEC_MATCH "disable_pathspec_match"
#define CHECK_PATHSPEC "check_pathspec"

#define IGNORE_CASE "ignore_case"
#define NO_FILEMODE "no_filemode"
#define NO_SYMLINKS "no_symlinks"
#define FROM_OWNER "from_owner"

#define INVALID "invalid"
#define SYMBOLIC "symbolic"

#define OLD "old"
#define NEW "new"
#define COMMITTER "committer"
#define MESSAGE "message"

#define SOFT "soft"
#define MIXED "mixed"
#define HARD "hard"

#define INEW               "index_new"
#define IMOD               "index_modified"
#define IDEL               "index_deleted"
#define IREN               "index_renamed"
#define ITYP               "index_typechange"

#define WNEW               "workdir_new"
#define WMOD               "workdir_modified"
#define WDEL               "workdir_deleted"
#define WTYP               "workdir_typechange"
#define WREN               "workdir_renamed"

#define IGNOREED           "ignored"

#define SHOW               "show"
#define FLAGS              "flags"
#define PATHS              "paths"

#define INC_UNTRACKED      "include_untracked"
#define INC_IGNORED        "include_ignored"
#define INC_UNMODIFIED     "include_unmodified"
#define EX_SUBMODULES      "exclude_submoduled"
#define REC_UNTRACKED_DIRS "recurse_untracked_dirs"
#define DISABLE_PATHSPEC   "diable_pathspec_match"
#define REC_IGNORED_DIRS   "recurse_ignored_dirs"
#define REN_HEAD_TO_IDX    "rename_head_to_index"
#define REN_IDX_TO_WDIR    "rename_index_to_workdir"
#define SORT_SENSI         "sort_case_sensitively"
#define SORT_INSENSI       "sort_case_insensitively"
#define REN_FROM_REWRITE   "renames_from_rewrites"
#define NO_REFRESH         "no_refresh"

#define STATUS           "status"
#define IDX_TO_WRK       "index_to_workdir"
#define HEAD_TO_IDX      "head_to_index"

#define UNTRACKED "untracked"
#define DIRTY "dirty"
#define ALL "all"
#define DEFAULT "default"

#define CHECKOUT "checkout"
#define REBASE "rebase"
#define MERGE "merge"
#define NONE "none"

#define RECURSE_YES "yes"
#define RECURSE_NO "no"
#define RECURSE_ONDEMAND "on_demand"

#define ANY "any"
#define BAD "bad"
#define _EXT1 "_ext1"
#define COMMIT "commit"
#define TREE "tree"
#define BLOB "blob"
#define TAG "tag"
#define _EXT2 "_ext2"
#define OFS_DELTA "ofs_delta"
#define REF_DELTA "ref_delta"

#define SSH "ssh"
#define HTTP "http"

#define BLAME_LINES_IN_HUNK "lines_in_hunk"

#define DIRECTION "direction"
#define STRING "representation"
#define SRC "src"
#define DEST "dest"
#define PUSH "push"
#define FETCH "fetch"
#define UNKNOWN "unknown"
#define FORCE "force"
#define ALL "all"
#define NONE "none"
#define AUTO "auto"
#define TOTAL "total"
#define DELTA "delta"
#define INDEXED_DELTAS "indexed_deltas"
#define BYTES "bytes"
#define RECEIVED "received"
#define INDEXED "indexed"

#define ORIGIN "origin"
#define OLD_LINENO "old linenr"
#define NEW_LINENO "old linenr"
#define LINES "lines"

#define OLD_START "old start"
#define OLD_LINES "old lines"
#define NEW_START "new start"
#define NEW_LINES "new lines"
#endif
