set( SRC_FILES
   ${SRC_DIR}/blame.c
   ${SRC_DIR}/blob.c
   ${SRC_DIR}/branch.c
   ${SRC_DIR}/checkout.c
   ${SRC_DIR}/cherrypick.c
   ${SRC_DIR}/clone.c
   ${SRC_DIR}/commit.c
   ${SRC_DIR}/common.c
   ${SRC_DIR}/config.c
   ${SRC_DIR}/diff.c
   ${SRC_DIR}/graph.c
   ${SRC_DIR}/ignore.c
   ${SRC_DIR}/index.c
   ${SRC_DIR}/indexer.c
   ${SRC_DIR}/ltk.c
   ${SRC_DIR}/luagi.c
   ${SRC_DIR}/merge.c
   ${SRC_DIR}/note.c
   ${SRC_DIR}/object.c
   ${SRC_DIR}/odb.c
   ${SRC_DIR}/oid.c
   ${SRC_DIR}/pack.c
   ${SRC_DIR}/patch.c
   ${SRC_DIR}/push.c
   ${SRC_DIR}/refdb.c
   ${SRC_DIR}/reference.c
   ${SRC_DIR}/reflog.c
   ${SRC_DIR}/remote.c
   ${SRC_DIR}/repository.c
   ${SRC_DIR}/reset.c
   ${SRC_DIR}/revwalk.c
   ${SRC_DIR}/stash.c
   ${SRC_DIR}/status.c
   ${SRC_DIR}/submodule.c
   ${SRC_DIR}/tag.c
   ${SRC_DIR}/tree.c
   ${SRC_DIR}/tree_builder.c
   ${SRC_DIR}/types.c
)
